//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Empleado
{
	public virtual int idEmpleado
	{
		get;
		private set;
	}

	public virtual string Nombre
	{
		get;
		set;
	}

	public virtual string Apellido2
	{
		get;
		set;
	}

	public virtual string Apellido1
	{
		get;
		set;
	}

	public virtual int Sexo
	{
		get;
		set;
	}

	public virtual DateTime FechaNacimiento
	{
		get;
		set;
	}

	public virtual int TipoDocumIdent
	{
		get;
		set;
	}

	public virtual string DocumIdent
	{
		get;
		set;
	}

	public virtual int DomiTipoVía
	{
		get;
		set;
	}

	public virtual string DomiNombreVía
	{
		get;
		set;
	}

	public virtual string DomiLocalidad
	{
		get;
		set;
	}

	public virtual string DomiCodPostal
	{
		get;
		set;
	}

	public virtual int DomiProvincia
	{
		get;
		set;
	}

	public virtual int DomiPais
	{
		get;
		set;
	}

	public virtual string DomiNúmero
	{
		get;
		set;
	}

	public virtual string DomiBloque
	{
		get;
		set;
	}

	public virtual string DomiEscalera
	{
		get;
		set;
	}

	public virtual string DomiPiso
	{
		get;
		set;
	}

	public virtual string DomiPuerta
	{
		get;
		set;
	}

	public virtual int LaboConvenio
	{
		get;
		set;
	}

	public virtual int LaboEmpresa
	{
		get;
		set;
	}

	public virtual int LaboCentro
	{
		get;
		set;
	}

	public virtual int LaboCategoría
	{
		get;
		set;
	}

	public virtual DateTime LaboFechaAlta
	{
		get;
		set;
	}

	public virtual DateTime LaboFechaBaha
	{
		get;
		set;
	}

	public virtual int LaboCausaBaja
	{
		get;
		set;
	}

	public virtual int LaboCNAE
	{
		get;
		set;
	}

	public virtual int LaboCNO94
	{
		get;
		set;
	}

	public virtual int LaboCNO11
	{
		get;
		set;
	}

	public virtual int LaboTipoEmpeado
	{
		get;
		set;
	}

	public virtual int LaboAntigüedad
	{
		get;
		set;
	}

	public virtual int LaboRelLaboral
	{
		get;
		set;
	}

	public virtual bool LaboExcedenteSectorIndustrial
	{
		get;
		set;
	}

	public virtual string SegSocNúmero
	{
		get;
		set;
	}

	public virtual int SegSocGrupoCotización
	{
		get;
		set;
	}

	public virtual int SegSocOcupaciónAT_EP
	{
		get;
		set;
	}

}

